### ISSUE TITLE
Argument substitution doesn't work with all queries

### ISSUE THREAD

**Issue by cmd410** [codehz/easy_sqlite3#4]
Consider the following:
```nim
import easy_sqlite3

proc getUserVersion(): tuple[value: int] {.importdb: "PRAGMA user_version".}
proc setUserVersion(arg: int) {.importdb: "PRAGMA user_version = $arg".}   # This doesn't work

var db = initDatabase(":memory:")

echo db.getUserVersion()
db.setUserVersion(1)
echo db.getUserVersion()
```
Here I try to set `user_version` pragma in the database to arbitrary integer value using parameter substitution analogous to `select_1` example in the readme. However, this code fails with an error:
```
Error: unhandled exception: near "$arg": syntax error [SQLiteError]
```
I wonder why.

**Comment by codehz** [comment]
This is the restriction of sqlite, the pragma command only support literal 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/13158903/230179087-82e5677c-96c0-4ccd-8c58-a17a4972776e.png">
You can only use the binding parameters where the expr is accepted, but this is not the case
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13158903/230179640-08134327-262a-4be5-bc0f-672caa8b69b2.png">
